### PR TITLE
replace broken Travis builds with GHA builds

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by kLabz** [comment]
You might want https://github.com/krdlab/setup-haxe/pull/24 to add latest development since travis was running on it too

**Comment by sebthom** [comment]
@kLabz I was looking at this. waiting for PR merge and release

**Comment by Simn** [comment]
@kLabz I don't know what any of this is, so feel free to merge! :P

**Comment by kLabz** [comment]
I guess it'd be better to wait for above mentioned PR to be merged and released so we can run github actions on development too. Shouldn't take too long, PR has already been reviewed.

Other than that, this PR seems fine, and CI [is working](https://github.com/sebthom/hx3compat/actions/runs/4005909012). Just not sure why that `on` config needed to be so complex?

**Comment by kLabz** [comment]
@sebthom setup-haxe 1.3.0 is released :)

**Comment by sebthom** [comment]
I added the latest release

**Comment by kLabz** [comment]
And [CI](https://github.com/sebthom/hx3compat/actions/runs/4015041454/jobs/6896297709) is fine with latest too :)
Thanks!

**Pull request merged**
